### ISSUE TITLE
[fastpages] Automated Upgrade

### ISSUE THREAD

**Issue by iriisyang** [iriisyang/Iris-Yang#7]
**crossover: 2.7/3
review: 2.9/3**

- [Fibonacci Classes](https://iriisyang.github.io/Iris-Yang/java/2022/09/25/fibonacci.html)
- [JavaScript](https://iriisyang.github.io/Iris-Yang/javascript/2022/09/25/javascript.html)
- [PBL plan](https://sarayu-pr11.github.io/teamGrapeSnails/markdown/2022/09/23/pbl-plan.html)

**Comment by tangalice** [comment]
0.9/1 For loop, while loop and recursion finished for fibonacci 

0.9/1 javascript feature of table (mean, mode, etc. )
